{{ if .Values.phpmyadmindeploy }}
apiVersion: v1
kind: Secret
metadata:
  name: {{.Release.Name}}-phpmyadmin-secret
  namespace: laravel
type: Opaque
data:
  database_password: a3ViZXJuZXRlcw==
  database_root_password: cGFzc3dvcmQ=

{{ end }}