{{ if .Values.phpmyadmindeploy }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}-phpmyadmin-deploy
  namespace: laravel
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin:{{.Values.tagpgpmyadmin}}
        ports:
        - containerPort: 80
        resources:
          limits:
              memory: {{.Values.phpmyadminMem}}
              cpu: {{.Values.phpmyadminCPU}}
          requests:
              memory: {{.Values.phpmyadminMemoRequest}}
              cpu: {{.Values.phpmyadminCPURequest}} 
        env:
        - name: PMA_HOST
          valueFrom:
            configMapKeyRef:
              name: {{.Release.Name}}-phpmyadmin-configmap
              key: host

        - name: PMA_PORT
          valueFrom:
            configMapKeyRef:
              name: {{.Release.Name}}-phpmyadmin-configmap
              key: port

        - name: PMA_USER
          valueFrom:
            configMapKeyRef:
              name: {{.Release.Name}}-phpmyadmin-configmap
              key: user
              
        - name: PMA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{.Release.Name}}-phpmyadmin-secret
              key: database_password

{{ end }}
