apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim-mysql
  namespace: laravel
spec:
  storageClassName: sc-mysql
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi