# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: mysql-configmap
#   namespace: laravel
# data:
#   name: mariadb
#   user: usuario


apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Release.Name}}-mysql-configmap
  namespace: {{.Values.namespace}}
data:
  name: {{ .Values.name }}
  user: {{ .Values.user }}


