{{ if .Values.phpmyadmindeploy }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Release.Name}}-phpmyadmin-configmap
  namespace: laravel 
data:
  user: {{.Values.user}}
  name: {{.Values.name}}
  host: {{.Values.host}}
  port: "3306"

{{ end }}