{{ if .Values.phpmyadmindeploy }}
apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-phpmyadmin
  namespace: laravel
spec:
  selector:
    app: phpmyadmin
  ports:
    - port: 80
  type: NodePort
{{ end }}