apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Release.Name}}-pv-claim-mysql
  namespace: {{.Values.namespace}}
spec:
  storageClassName: sc-mysql
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi