apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Release.Name}}-pv-claim-laravel
  namespace: {{.Values.namespace}}
spec:
  storageClassName: sistemaficheros
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi