apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}-laravel-deployment
  namespace: {{.Values.namespace}}
spec:
  selector:
    matchLabels:
      app: laravel
  template:
    metadata:
      labels:
        app: laravel
    spec:
      
      containers:
      - name: laravel
        ports:
        - containerPort: 8000
        image: bitnami/laravel:{{.Values.taglaravel}}
        env:
        - name: LARAVEL_DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              name: {{.Release.Name}}-laravel-configmap
              key: host

        - name: LARAVEL_DATABASE_PORT_NUMBER
          valueFrom:
            configMapKeyRef:
              name: {{.Release.Name}}-laravel-configmap
              key: port

        - name: LARAVEL_DATABASE_USER
          valueFrom:
            configMapKeyRef:
              name: {{.Release.Name}}-laravel-configmap
              key: user

        - name: LARAVEL_DATABASE_NAME
          valueFrom:
            configMapKeyRef:
              name: {{.Release.Name}}-laravel-configmap
              key: name

        - name: LARAVEL_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: database_password

      #   volumeMounts:
      #     - mountPath: "/app"
      #       name: pv-storage-laravel

      # volumes:
      #   - name: pv-storage-laravel
      #     persistentVolumeClaim:
      #       claimName: pv-claim-laravel      

        # livenessProbe:
        #   httpGet:
        #     path: /health
        #     port: 8000
        #   initialDelaySeconds: 60
        #   periodSeconds: 20
        #   timeoutSeconds: 5      

        # readinessProbe:
        #   tcpSocket:
        #     port: 8000
        #   initialDelaySeconds: 30
        #   periodSeconds: 10
        #   timeoutSeconds: 5  

