apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: laravel
type: Opaque
data:
  database_password: a3ViZXJuZXRlcw==
  database_root_password: cGFzc3dvcmQ=


# apiVersion: v1
# kind: Secret
# metadata:
#   name: mysql-secret
#   namespace: laravel
# type: Opaque
# data:
#   database_password: "{{ .Values.database_password }}"
#   database_root_password: "{{ .Values.database_root_password }}"
  