# apiVersion: apps/v1
# kind: StatefulSet
# metadata:
#   name: mysql-stateful
# spec:
#   selector:
#     matchLabels:
#       app: db
#   serviceName: mariadb-svc
#   template:
#     metadata:
#       labels:
#         app: db
#     spec:
#       #terminationGracePeriodSeconds: 10  
#       containers:
#       - name: mysql
#         image: mysql:8.4        
#         ports:
#         - containerPort: 3306
#         env:
#         - name: MYSQL_USER
#           valueFrom:
#             configMapKeyRef:
#               name: mysql-configmap
#               key: user

#         - name: MYSQL_PASSWORD
#           valueFrom:
#             secretKeyRef:
#               name: mysql-secret
#               key: database_password

#         - name: MYSQL_ROOT_PASSWORD
#           valueFrom:
#             secretKeyRef:
#               name: mysql-secret
#               key: database_root_password

#         - name: MYSQL_DATABASE
#           valueFrom:
#             configMapKeyRef:
#               name: mysql-configmap
#               key: name
#         volumeMounts:
#         - name: pv-storage-mysql
#           mountPath: /var/lib/mysql    
#       volumes:
#         - name: pv-storage-mysql
#           persistentVolumeClaim:
#             claimName: pv-claim-mysql

  # volumeClaimTemplates:
  #   - metadata:
  #       name: db-storage      
  #     spec:
  #       storageClassName: sc-mysql
  #       accessModes: ["ReadWriteOnce"]
  #       resources:
  #         requests:
  #           storage: 1Gi


apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{.Release.Name}}-mysql-statefulset
  namespace: laravel
spec:
  serviceName: mariadb-svc
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:    
      containers:
      - name: mysql
        image: mysql:{{.Values.tagmysql}}
        resources:
          limits:
              memory: {{.Values.mysqlMem}}
              cpu: {{.Values.mysqlCPU}}
          requests:
              memory: {{.Values.mysqlMemoRequest}}
              cpu: {{.Values.mysqlCPURequest}}
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: {{.Release.Name}}-mysql-configmap
              key: user

        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: database_password

        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: database_root_password

        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: {{.Release.Name}}-mysql-configmap
              key: name
        
        volumeMounts:
        - name: pv-storage-mysql
          mountPath: /var/lib/mysql    
      volumes:
        - name: pv-storage-mysql
          persistentVolumeClaim:
            claimName: pv-claim-mysql

        # resources:
        #   limits:
        #       memory: {{.Values.mysqlMem}}
        #       cpu: {{.Values.mysqlCPU}}
        #   requests:
        #       memory: {{.Values.mysqlMemoRequest}}
        #       cpu: {{.Values.mysqlCPURequest}}      

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: mysql-deployment
#   namespace: laravel
# spec:
#   selector:
#     matchLabels:
#       app: db
#   template:
#     metadata:
#       labels:
#         app: db
#     spec:    
#       containers:
#       - name: mysql
#         image: mysql:8.4
#         ports:
#         - containerPort: 3306
#         env:
#         - name: MYSQL_USER
#           valueFrom:
#             configMapKeyRef:
#               name: mysql-configmap
#               key: user

#         - name: MYSQL_PASSWORD
#           valueFrom:
#             secretKeyRef:
#               name: mysql-secret
#               key: database_password

#         - name: MYSQL_ROOT_PASSWORD
#           valueFrom:
#             secretKeyRef:
#               name: mysql-secret
#               key: database_root_password

#         - name: MYSQL_DATABASE
#           valueFrom:
#             configMapKeyRef:
#               name: mysql-configmap
#               key: name