apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume-laravel
  namespace: {{.Values.namespace}}
  labels:
    type: local
spec:
  storageClassName: sistemaficheros
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/laravel"