apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume-mysql
  namespace: laravel
  labels:
    type: local
spec:
  storageClassName: sc-mysql
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/mysql"