apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim-laravel
  namespace: laravel
spec:
  storageClassName: sistemaficheros
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi